### ISSUE TITLE
Can't inject service to another service that injects it

### ISSUE THREAD

**Issue by maskedman0** [mayajs/maya#46]
## 📝 Describe the bug

Can't inject service to dependent service and vice versa
e.g. (service a >> service b >> service c >> service a)

**To Reproduce**

1. Create 2 service for their respective controllers using the command: `maya generate service <service-name>`
2. Make sure both service are decorated with "@Injectable()" decorator from "@maya/common"
3. Inject service 1 to service 2
4. Inject service 2 to service 1
5. Run command: `maya serve`

### Sample Service 1 Code
```javascript

@Injectable()
export class Sample1Service {
  constructor(private service: Sample2Service) {}
}
```

### Sample Service 2 Code
```javascript

@Injectable()
export class Sample2Service {
  constructor(private service: Sample1Service) {}
}
```

### Terminal Error
![image](https://user-images.githubusercontent.com/62224113/77142418-fbd93980-6aba-11ea-8184-f466ef6324ef.png)

**Comment by mackignacio** [comment]
This is a circular dependency issue. You can't inject a class that has a dependency on the class your are injecting for. This is a bad coding practice. You can see a detailed discussion on this in [stackoverflow question - Is circular dependency good or bad](https://stackoverflow.com/questions/26804803/is-circular-dependency-good-or-bad). My advice is to restructure your code.

**Comment by mackignacio** [comment]
Closing this issue because this is not a MayaJS issue.
