### ISSUE TITLE
🐞 Invalid class names generated after `maya generate <type> <name>` command

### ISSUE THREAD

**Issue by maskedman0** [mayajs/maya#48]
## 📝 Describe the bug
Invalid class names generated after `maya generate <type> <name>` command

**To Reproduce**

1. Create a maya project using the command: `maya new <project-name>`
2. Create a controller inside the project using the command: `maya g r <dash-seperated-route-name>`
3. View the generated controller and service

**Expected behavior**
Generate class names with pascal casing

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/62224113/77736319-08273e80-7047-11ea-9ac9-764b3620d4e5.png)

## ⚙️ Component
maya/cli

**Comment by mackignacio** [comment]
This is an issue on the CLI not on the core mayajs library. This is already fix on [PR](https://github.com/mayajs/cli/pull/16) on mayajs/cli repo. Closing this issue.
