### ISSUE TITLE
You call this a framework?

### ISSUE THREAD

**Issue by truetrollolol** [mayajs/maya#57]
## 📝 Description

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when a developer has an inflated ego.

**Describe the solution you'd like**
Please rename this to **MAYA NODEJS BOILERPLATE**

**Describe alternatives you've considered**
Delete the whole repo

## ⚙️ Component

All of them

## 📋 Todo:

- [ ] Rename to  **MAYA NODEJS BOILERPLATE**
- [ ] Delete the whole repo

## 🔍 Additional Info

Be humble.

**Comment by Mackignacio** [comment]
Trolls are not allowed to contribute to an open-source project. Please read the GitHub policy first.
